pipeline {
  agent {
    label 'AGENT-1'
  }
  options {
    timeout(time: 5, unit: 'MINUTES')
    disableConcurrentBuilds()
  }
  environment {
    DEBUG = 'true'
    //appversion = '' //this is global varible we can use any where inthe pipeline
    region = 'us-east-1'
    account_id = '688567303455'
    project = 'expense'
    environment = 'dev'
    component = 'backend'
  }

  stages{
    stage('debug') {
      steps {
        echo 'debugging..'
        sh 'env'
      }
    }

    stage('Read The Version') {
      steps {
        script {
          def packageJson = readJSON file: 'Backend/package.json'
          // appversion = packageJson.version
          // echo "App version: ${appversion}"
          env.appVersion = packageJson.version
          echo "App version: ${env.appVersion}"
        }
      }
    }

    stage('install dependencies'){
      steps {
        dir('Backend') {
          sh 'npm install'
        }
      }
    }
    // stage('Docker build'){
    //   steps {
    //     sh """
    //       docker build -t basavaraj0509/backend:${appversion} .
    //       docker images
    //     """
    //   }
    // }
    stage('Docker Build'){
      steps {
        withAWS(region: 'us-east-1', credentials: 'aws-creds'){
          dir('Backend'){
            sh """
              aws ecr get-login-password --region ${region} | docker login --username AWS --password-stdin ${account_id}.dkr.ecr.us-east-1.amazonaws.com
           
              docker build -t ${account_id}.dkr.ecr.us-east-1.amazonaws.com/${project}/${environment}/${component}:${appVersion} .
 
              docker images
 
              docker push ${account_id}.dkr.ecr.us-east-1.amazonaws.com/${project}/${environment}/${component}:${appVersion}
            """
          }
        }
      }
    }
    stage('SonarQube analysis'){
      environment {
        SCANNER_HOME = tool 'sonar-7.0' //scanner-configuration
      }
      steps {
        //sonar server injection
        dir('Backend') {
          withSonarQubeEnv('sonar-7.0') {
            sh '$SCANNER_HOME/bin/sonar-scanner'
            //genaric scanner, it autmatically understand the language and provide scan results.
          }
        }
      }
    }
    stage('SQuality Gate') {
      steps {
        dir('Backend') {
          timeout(time: 5, unit: 'MINUTES') {
            waitForQualityGate abortPipeline: true
          }
        }
      }
    }
    stage('Deploy'){
      steps {
        withAWS(region: 'us-east-1', credentials: 'aws-creds'){
          dir('Backend/helm') {
            sh """
              aws eks update-kubeconfig --region ${region} --name ${project}-${environment}
              sed -i 's/IMAGE_VERSION/${appVersion}/g' values-${environment}.yaml
              helm upgrade --install ${component} -n ${project}-${environment} -f values-${environment}.yaml .
            """
          }
        }
      }
    }
  }
  post {
    always {
      echo 'This section always runs!'
      deleteDir() //in jenkins this function will delete the workspace directory of the job on the agent (VM/container)
    }
    success {
      echo 'This section runs when pipeline sucess'
    }
    failure {
      echo 'This section runs when pipeline failed' 
    }
  }
}