kind: Service
apiVersion: v1 

metadata: 
  name: frontend
  namespace: expense-dev
 
spec: 
  type: {{ .Values.service.type }}
  selector:
    app: frontend
    tier: web
    project: expense
  ports: 
  - name: frontend-port 
    protocol: TCP
    port: 80
    targetPort: 8080